# Generated by Django 2.1.7 on 2019-03-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0002_auto_20190321_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='user',
        ),
    ]
