# Generated by Django 2.1.7 on 2019-03-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0003_auto_20190327_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='task_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
