# Generated by Django 2.1.7 on 2019-03-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0006_auto_20190321_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
