# Generated by Django 2.1.7 on 2019-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0007_remove_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
